---
header:
  - license:
      spdx-id: Apache-2.0
      copyright-owner: spidernet-io
      pattern: |
        Copyright|Apache-2.0
      content: |
        Copyright 2022 Authors of spidernet-io
        SPDX-License-Identifier: Apache-2.0
    paths:
      - '**/*.go'
      - '**/*.sh'
    paths-ignore:
      - 'vendor'
      - 'pkg/nodemanager/mocks/mock_manager_interface.go'
    comment: on-failure
  - license:
      content: |
        Copyright 2019 The Kubernetes Authors
        SPDX-License-Identifier: Apache-2.0
    paths:
      - '**/*.go'
      - '**/*.sh'
    paths-ignore:
      - 'vendor'
      - 'pkg/nodemanager/mocks/mock_manager_interface.go'
    comment: on-failure
  - license:
      content: |
        Copyright 2014 The vektra Authors
        SPDX-License-Identifier: BSD-3-Clause
    paths:
      - '**/*.go'
      - '**/*.sh'
    paths-ignore:
      - 'vendor'
    comment: on-failure

